---
 - name: change the configuration of tomcat file
   hosts: webservers
   become: true
   tasks:
     - name: changing the tomcat-users file
       template: src=/home/ansible/tomcat-users.xml.j2 dest=/opt/apache-tomcat-7.0.109/conf/tomcat-users.xml
     - name: changing the context file
       template: src=/home/ansible/context.xml.j2 dest=/opt/apache-tomcat-7.0.109/webapps/manager/META-INF/context.xml    
